title:<p align="center"> Tori Robinson  </p>
theme: jekyll-theme-minimal
logo: Design uten navn (2).png

title: <p align="center"> Chris Tran </p>


description:
  <p align="center">
   </p>
  <p align="justify">
  I hava a backroung in Bioscience and is currently pursing a career as a Data Analyst
  <br><br>
  </p>
