title: Tori Robinson 
theme: jekyll-theme-minimal
a {
    color: green !important; /* Change all links to green */
    text-decoration: none; /* Optional: Remove underline */
}

a:hover {
    color: darkgreen; /* Optional: Change to dark green on hover */
}

